# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Crowd Management' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Crowd Management


pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database’
pod 'Firebase/Storage’



end
